### ISSUE TITLE
"Syntax error: newline unexpected" when running the script.

### ISSUE THREAD

**Issue by GOTO-GOSUB** [springfielddatarecovery/BOINConPi#1]
Thank you for producing this tool. I have tried to use it today and got as far as this part:

` sudo  ./boinconpi.sh`

... when the following error is returned:

`./boinconpi.sh: 8: ./boinconpi.sh: Syntax error: newline unexpected`

Would you please be able to take a look ? This was seen on a 4GB Pi 4 with the latest build of Pi OS 64 bit.

**Comment by springfielddatarecovery** [comment]
Thank you for reporting this! This was an issue with the command given in the readme. If you run `rm boinconpi.sh` and then run the new command in the readme, it should work for you. Let me know if it gives you any issues :).
